# Generated by Django 5.0.6 on 2024-07-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('approve', 'Approve'), ('not_approved', 'Not Approved')], default='not_approved', max_length=16, null=True),
        ),
    ]
