# Generated by Django 5.0.6 on 2024-06-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('attachment_file', models.FileField(blank=True, max_length=500, null=True, upload_to='reader/book/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
